theme = "blowfish"
baseURL = "https://ohwowbill.com/"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
summaryLength = 60
hasCJKLanguage = true

buildDrafts = false
buildFuture = false
enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10
